import React from "react";
import '../styles/globals.scss';

export default function RootLayout({ children }:{children:React.ReactNode}) {
  return (
    <html lang="en">
      <head>
        <title>Retaehc | Pop</title>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Generated by create next app" />
      </head>
      <body>{children}</body>
    </html>
  )
}
