name: Docker Image CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches: [ "main" ]
env:
  PROJECT_ID: ${{ secrets.CLOUD_RUN_PROJECT_NAME }}
  REGION: us-east1
  # project-name but it can be anything
  REPO_NAME: Retaehc-pop
  
jobs:
  build-and-deploy:
    name: Setup, Build, Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - id: 'auth'
        uses: "google-github-action/auth@v0"
        with:
          credentials_json: "${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT }}"
        
      - name: Setup Cloud SDK
        uses: google github-action/setup-gcloud@v0
      
      - name: autherize Docker push
        run: gcloud auth configure-docker
        
      - name: Build and Create Docker Image
        run: |-
          docker build . --tag gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA
        
      - name: Push the image to the Google Container Registry (GCR)
        run: |-
          docker push gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA
          
      - name: Deploy
        run: |-
          gcloud run deploy $REPO_NAME \
          --region $REGION \
          --image gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA \
          --platform "managed" \ 
          --quiet
